version: '3.9'

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    image: react-build:latest
    ports:
      - "80:80"
    restart: always
